[project]

#   /    Context:                     https://ctx.ist
# ,'`./    do you remember?
# `.,'\
#   \    Copyright 2026-present Context contributors.
#                 SPDX-License-Identifier: Apache-2.0

site_name = "ctx: do you remember?"
site_description = "ctx provides temporal continuity across sessions"
site_author = "Jose Alekhinne <alekhinejose@gmail.com>"
site_url = "https://ctx.ist/"
repo_url = "https://github.com/ActiveMemory/ctx"
repo_name = "ActiveMemory/ctx"
copyright = """
Copyright &copy; 2026&ndash;present Context conributors.<br>
Context's code is distributed under
<a href="https://github.com/ActiveMemory/ctx/blob/main/LICENSE"><strong>Apache (v2.0)</strong></a>.<br>
The documentation on this website is distributed under
<a href="https://creativecommons.org/licenses/by/4.0/deed.en"><strong>CC-BY-4.0</strong></a>.
"""

nav = [
  { "Getting Started" = "index.md" },
  { "Prompting Guide" = "prompting-guide.md" },
  { "ctx and Similar Tools" = "comparison.md"},
  { "CLI Reference" = "cli-reference.md" },
  { "Context Files" = "context-files.md" },
  { "ralph + ctx" = "ralph-loop.md" },
  { "Integrations" = "integrations.md" },
  { "Version History" = "versions.md" },
  { "Security" = "security.md" },
  { "Blog" = [
    { "index" = "blog/index.md" },
    { "Building ctx Using ctx" = "blog/2026-01-27-building-ctx-using-ctx.md" }
  ]}
]

#extra_css = ["stylesheets/extra.css"]
#extra_javascript = ["javascripts/extra.js"]

[project.theme]
favicon = "images/favicon-32.png"
logo = "images/ctx-favicon-32.png"
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
#logo = "images/ctx-favicon-128.png"
#repo = "lucide/smile"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/ActiveMemory/ctx"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/kampus"

[project.extra]
generator = false
